version: "3.3"

services:
  startersaas-react-spa:
    container_name: startersaas-react-spa
    build:
      context: .
      dockerfile: docker/dev/Dockerfile
    ports:
      - "${APP_PORT}:3010"
    volumes:
      - .:/app
      - node_modules:/app/node_modules

volumes:
  node_modules:
